#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL

  ALTER USER ${POSTGRES_USER} WITH SUPERUSER CREATEROLE CREATEDB;

  REVOKE ALL ON DATABASE ${POSTGRES_DB} FROM PUBLIC;
  REVOKE ALL ON SCHEMA public FROM PUBLIC;

  GRANT ALL PRIVILEGES ON DATABASE ${POSTGRES_DB} TO ${POSTGRES_USER};
  GRANT ALL ON SCHEMA public TO ${POSTGRES_USER};

EOSQL